//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabase.Geography.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banca
    {
        public string IdBanca { get; set; }
        public string CodBanca { get; set; }
        public string DescBanca { get; set; }
        public string fk_Nazione_Id { get; set; }
        public string Abi { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public Nullable<System.DateTime> DataCessato { get; set; }
    }
}
