//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabase.Geography.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comune
    {
        public string IdComune { get; set; }
        public string fk_Provincia_Id { get; set; }
        public string CodComune { get; set; }
        public string DescComune { get; set; }
        public string CapGenerico { get; set; }
        public string CodIstat { get; set; }
        public string CodCatastale { get; set; }
        public string CodUfficioRegistro { get; set; }
        public string fk_AreaCompetenza_Id { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public Nullable<System.DateTime> DataCessato { get; set; }
    
        public virtual Provincia Provincia { get; set; }
    }
}
