//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabase.Geography.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GeographyEntities : DbContext
    {
        public GeographyEntities()
            : base("name=GeographyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banca> Banca { get; set; }
        public virtual DbSet<Comune> Comune { get; set; }
        public virtual DbSet<Nazione> Nazione { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Regione> Regione { get; set; }
        public virtual DbSet<Utente> Utente { get; set; }
    }
}
