//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabase.Geography.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nazione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nazione()
        {
            this.Regione = new HashSet<Regione>();
        }
    
        public string IdNazione { get; set; }
        public string CodNazione { get; set; }
        public string DescNazione { get; set; }
        public string SiglaStatoNazione { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public Nullable<System.DateTime> DataCessato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regione> Regione { get; set; }
    }
}
