//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabase.Geography.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Provincia()
        {
            this.Comune = new HashSet<Comune>();
        }
    
        public string IdProvincia { get; set; }
        public string fk_Regione_Id { get; set; }
        public string CodProvincia { get; set; }
        public string DescProvincia { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public Nullable<System.DateTime> DataCessato { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comune> Comune { get; set; }
        public virtual Regione Regione { get; set; }
    }
}
