//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDatabase.Geography.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Regione()
        {
            this.Provincia = new HashSet<Provincia>();
        }
    
        public string IdRegione { get; set; }
        public string fk_Nazione_Id { get; set; }
        public string CodRegione { get; set; }
        public string DescRegione { get; set; }
        public Nullable<System.DateTime> DataInserimento { get; set; }
        public Nullable<System.DateTime> DataAggiornamento { get; set; }
        public Nullable<System.DateTime> DataCessato { get; set; }
    
        public virtual Nazione Nazione { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Provincia> Provincia { get; set; }
    }
}
